<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fishman's Adventure</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body class="d-flex align-items-center justify-content-center bg-dark vh-100 m-0 p-0">
    <script type="module">
        import init from './fishmans_adventure.js'

        init().catch((error) => {
            if (!error.message.startsWith("Using exceptions for control flow, don't mind me. This isn't actually an error!")) {
                throw error;
            }
        });
    </script>

    <div class="container text-center">
        <canvas id="fishmans_adventure" width="1280" height="720"
            class="border border-light shadow-lg rounded"></canvas>
        <p class="text-light mt-3">Fishman's Adventure</p>
    </div>

</body>

</html>